#!/bin/sh

usage_msg="usage: $0 ( start | stop )"

# check for cmd line arguments
if [ $# -lt 1 ]
then
    echo $usage_msg >&2
    exit 1
fi

case $1 in
    start)
        echo "Starting aesdsocket..."
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket..."
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo $usage_msg >&2
        exit 1
esac