#!/bin/sh

function print_usage() {
    echo "$0: load/unload aesd char device into kernel"
    echo "usage: $0 ( start | stop )"
}

if [ $# -lt 1 ]
then
    print_usage
    exit 1
fi

MODULE_DIR=/lib/modules/$(uname -r)/aesd-char-driver/

case $1 in
    start)
        ${MODULE_DIR}/aesdchar_load
    ;;
    stop)
        ${MODULE_DIR}/aesdchar_unload
    ;;
    *)
        print_usage
        echo "Unknown option: $1"
        exit 1
    ;;
esac

exit 0